name: Create release
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for github-action-get-previous-tag
      - name: Get previous tag
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get next minor version
        id: semver
        uses: 'WyriHaximus/github-action-next-semvers@v1'
        with:
          version: ${{ steps.previoustag.outputs.tag }}
          
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.5
        with:
          type: 'tar'
          filename: 'release/sei.tar.gz'
          command: "mkdir -p release"
          
      - name: Create Release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: ${{ steps.semver.outputs.patch }}
          artifacts: "release/sei.tar.gz"
